# Generated by Django 4.0.3 on 2022-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='aqi_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='main_pollutant_us',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
