# Generated by Django 3.2.8 on 2021-10-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug_fan', max_length=75),
            preserve_default=False,
        ),
    ]
