# Generated by Django 3.2.8 on 2021-10-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=75, unique=True, verbose_name='URL'),
        ),
    ]
