# Generated by Django 3.2.9 on 2021-11-03 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 11, 3, 13, 48, 8, 943826, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
