# Generated by Django 4.0.3 on 2022-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20211103_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=455)),
                ('file_pdf', models.FileField(upload_to='docs')),
            ],
        ),
    ]
