# Generated by Django 4.0.3 on 2022-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=2650),
        ),
    ]
